services:
  - type: web
    name: travel-planning-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: ZHIPU_API_KEY
        sync: false
      - key: PEXELS_API_KEY
        sync: false
